# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WB_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WB_swift
  pod "Alamofire"
  pod "HandyJSON"
  pod "IQKeyboardManagerSwift"
  pod "Kingfisher"
  pod "RxBlocking"
  pod "RxCocoa"
  pod "RxRelay"
  pod "RxSwift"
  pod "SnapKit"
end
